export const ISLOGIN = 'ISLOGIN';
export const ERRORS = 'ERRORS';
export const SUCCESS = 'SUCCESS';
export const GENERAL_ONLOAD = 'GENERAL_ONLOAD';
export const LOGOUT = 'LOGOUT'
export const MODAL = 'MODAL'
export const event = {
    GET_UPCOMING_EVENTS: 'GET_UPCOMING_EVENTS',
    GET_PAST_EVENTS: 'GET_PAST_EVENTS',
    GET_UPCOMING_EVENTS_ONLOAD: 'UPCOMING_EVENTS_ONLOAD',
    GET_PAST_EVENTS_ONLOAD: 'GET_PAST_EVENTS_ONLOAD',
    CREATE_EVENT: 'CREATE_EVENT'
};

export const GET_DIRECTION_LOADING = 'GET_DIRECTION_LOADING';
export const GET_DIRECTION = 'GET_DIRECTION';
export const GET_DIRECTION_ERROR = 'GET_DIRECTION_ERROR';

export const GET_GEOLOCATION_LOADING = 'GET_GEOLOCATION_LOADING';
export const GET_GEOLOCATION = 'GET_GEOLOCATION';
export const GET_GEOLOCATION_ERROR = 'GET_GEOLOCATION_ERROR';

export const GET_PLACE_LOADING = 'GET_PLACE_LOADING';
export const GET_PLACE = 'GET_PLACE';
export const GET_PLACE_ERROR = 'GET_PLACE_ERROR';

export const GET_LATLONG_LOADING = 'GET_LATLONG_LOADING';
export const GET_LATLONG = 'GET_LATLONG';
export const GET_LATLONG_ERROR = 'GET_LATLONG_ERROR';

export const GET_ALL_USER = 'GET_ALL_USER'
export const GET_GOOGLE_VISIONS_RESULT = 'GET_GOOGLE_VISIONS_RESULT'
export const CHANGE_STATUS_KEY = 'CHANGE_STATUS_KEY'

export const member = {
    GET_STATUS_INVITED_PENDING: 'GET_STATUS_INVITED_PENDING',
    GET_STATUS_INVITED_PENDING_ONLOAD: 'GET_STATUS_INVITED_PENDING_ONLOAD'
}

