export const ISLOGIN = 'ISLOGIN';
export const ERRORS = 'ERRORS';
export const SUCCESS = 'SUCCESS';
export const GENERAL_ONLOAD = 'GENERAL_ONLOAD';
export const LOGOUT = 'LOGOUT'
export const event = {
    GET_UPCOMING_EVENTS: 'GET_UPCOMING_EVENTS',
    GET_PAST_EVENTS: 'GET_PAST_EVENTS',
    GET_UPCOMING_EVENTS_ONLOAD: 'UPCOMING_EVENTS_ONLOAD',
    GET_PAST_EVENTS_ONLOAD: 'GET_PAST_EVENTS_ONLOAD',
    CREATE_EVENT: 'CREATE_EVENT'
}


